services:
  
  nats-server:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  plaza-ms:
    build:
      context: ./plaza-ms
      dockerfile: dockerfile
    volumes:
      - ./plaza-ms/src:/app/src:cached
    environment:
      - PORT=3000
    ports:
      - 4000:3000
    command: npm run start:dev

  cocina-ms:
    build:
      context: ./cocina-ms
      dockerfile: dockerfile
    volumes:
      - ./cocina-ms/src:/app/src:cached
    environment:
      - PORT=3000
    ports:
      - 5000:3000
    command: npm run start:docker:dev


